version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: root

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  web:
    build: .
    command: gunicorn msmeEcomm.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://myuser:root@db:5432/mydb

  celery:
    build: .
    command: celery -A msmeEcomm worker --loglevel=info
    depends_on:
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A msmeEcomm beat --loglevel=info
    depends_on:
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  postgres_data:
